//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodWaste.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public string Food { get; set; }
        public int ExpireDate { get; set; }
        public string State { get; set; }
        public Nullable<int> AssignEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
